architecture:
  dtype:
    param: float32
    activation: bfloat16
  n_embd: 256
  n_layers: 2
  bias: true
  dropout: 0.0
  n_head: 4
  block_size: 128
  layer_norm_eps: 1.0e-05
  rope: true
  vocab_size: 100288
  intermediate_size: -1
eval:
  evaluations: []
tokenizer:
  backend: tiktoken
  name: cl100k_base
  huggingface:
    use_fast: true
    use_remote_code: false
logging:
  plots:
    save: false
  report_interval: 4
  checkpoint_interval: 1000000
  validation_interval: 1000000
  wandb: false
optimization:
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  lr: 0.0003
  warmup_pct: 0.005
  decay_pct: 0.01
training:
  batch_size: 8
  per_device_batch_size: 8
  tokens: 8000
  warmup_pct: 0.01
  decay_pct: 0.1
  validation: false
  evaluate: false
  dataset:
  - name: synthetic
    rate: 1.0
    style: PMD
    suffix: ''
  validation_steps: 8
job: gpt/train/pretrain
request:
  min_chips: 0
  n_shards: 1
